(ns bookofcalmquotes.quotes
  (:require [bookofcalmquotes.db :as db]
            [bookofcalmquotes.twitter :as twitter]
            [taoensso.timbre :as timbre :refer :all]))

(defn insert-quote! [text]
  (cond
    (db/has-quote? text)
    (warn "The calming quote '" text "' is already in the db")
    (not (twitter/is-in-bounds? text))
    (warn "Tweet is not within the 140 char limit actual: " (count text))
    :else (db/insert-quote text)))

(defn init-quote-listing [qs]
  (doseq [quote qs]
    (insert-quote! quote)))

(init-quote-listing
 [
  "Add a dab of lavender to milk. Leave town with an orange, and pretend you're laughing at it."
  "Start every meal with something new - fruit or vegetables"
  "Recognize the difference between having and living."
  "Work on having positive thoughts. Pay particular attention to speaking positive words."
  "Use up nervous energy by fingering worry beads."
  "Nothing soaks away facial stress and tension quite like a damp, hot towel."
  "When all else fails in a stressful day, go somewhere quiet and dark."
  "The most important skill in staying calm is not to lose sleep over small issues."
  "For your own sake, forgive quickly and freely."
  "Repeat to yourself: \"Every moment, I feel calmer and calmer\" and you'll fool yourself calm."
  "Only take on what you can do - then politely, but firmly, turn down other requests."
  "It's marvelous how quickly many worries dissolve when you write them down on a piece of paper."
  "Tense your muscles. The contrast between tense and relaxed should indicate what relaxed feels like."
  "It is almost impossible to feel tense when you're concentrating on a Tai-Chi routine."
  "By adding a little rose oil to your massage oil, you can make the experience doubly effective."
  "Gaze upon some fish. Merely watching them is like gazing on a seascape."
  "Take to the waves. It can contribute to a growing sense of calm."
  "Ginseng, if taken regularly, can relax the nervous system."
  "Physical exertion counters the negative effects of stress."
  "Pretend that others see you as a calm person, and in no time you'll be a calm person."
  "The more you delegate, the more comfortable and capable you become with the practice."
  "Add a drop of lavender to your bath and soon, you will soak yourself calm."
  "Grow plants. The more oxygen you can get, the calmer you will become."
  "Take wonder in the small things you do. Cultivate this skill, and you'll find peace."
  "A chair that allows you sit erect is probably your best choice for sitting."
  "Learn from the calmness of children. Watch as they live every moment for the pleasure of the moment"
  "Even thought sunsets may sometimes be sad, they are always peaceful."
  "Wear donald duck underpants."
  "Imagine every day is a holiday. Do one little thing that stimulates this."
  "Do your stress levels a favour and take on changes one at a time."
  "Recognize that there is a time for stimulation, and a time for calm"
  "The fewer things you must do in life, the fewer things you own, the fewer are the stresses."
  "When you find yourself under pressure do something different."
  "Have you ever noticed how relaxed you feel the moment you remove your watch? Throw it away."
  "If you feel you need it, take brief cat naps throughout the day"
  "Eat more beans, lentils, peas, nuts, seeds, wheatgerm, wholegrains, and dairy foods."
  "Miss a phone call. Appreciate that important calls always ring back."
  "Pretend it's Saturday"
  "Some colors have a magical ability to instil calm in a troubled mind. Gaze on a blueberry."
  "Approach something with your full attention and an open-mind, and you'll find pleasure."
  "If you set your own agenda, you'll have much more time to become calm."
  "Add three drops of orange blossom oil to a cup of water. Spray it to feel relaxed."
  "Recognize choices. When you can see your choices, you will feel free."
  "Walk every day - Not because you have to, but to improve your attitude."
  "Running is one of life's antidotes to stress"
  "To avoid the stresses of debt, think about what you can afford to spend."
  "Christmas carols and lullabies have a unique ability to soothe. Use them all year round."
  "Milk helps you to relax and become calm."
  "Do whatever is necessary to get as much sleep as you feel you need."
  "Massage your eyebrows."
  "Concentrate on silence. When it comes, dwell on what it sounds like."
  "Be content with what you are - you'll be much more relaxed as a result."
  "The relaxation of love-making works on many different levels."
  "A cold body is seldom calm. Feeling calm follows feeling warm."
  "Your eyes are at their most relaxed when they are focused on distant objects."
  "Make a practise of looking for the best in people and situations."
  "When you're feeling under pressure, do something different. Roll up your sleeves. Eat an orange."
  "Start every journey ten minutes early."
  "When you rest, you are king. Look at the peacocks on the lawn. Survey your own calm kingdom."
  "Treat your work as important, and the satisfaction that flows will work towards helping you unwind"
  "Small print is custom-designed to induce frustration. Make that text larger."
  "Some of the most powerful acupressure points can be found at the temples."
  "There's nothing like a change to break the stress patterns that build throughout the day."
  "The higher above the ground you feel, the closer you will be to feeling calm."
  "Say your prayers, to achieve transquillity."
  "Know when to stop. When you know your stress levels are rising, stop what you are doing."
  "Float in a bathtub, and weightlessly feel your tensions dissolve."
  "Rest in a tub. Lower the lights, and add a few drops of lavender."
  "Barricade the door for an hour a day. Shut yourself out from interruption."
  "Indulge yourself by being generous. The person who will feel most uplifted will be you."
  "Take comfort in the fact that most things which take place in your thoughts, never eventuate."
  "Agree to discuss an issue in detail at a later date. Be surprised by how peacefully that can happen"
  "Take the time to methodically and slowly brush your hair. Brush in the calm."
  "There's nothing like a degree of success to help you become relaxed, as trivial as it may be."
  "Contrary to what you may tell yourself, you have all the time in the world."
  "Offer a compliment."
  "A smile relaxes all the major facial muscles."
  "Sitting in the front seat is stressful. Sit in the back seat, and journey while sharing the calm."
  "Have calm thoughts. Picture calm scenes. Recall calm sounds."
  "Eat more fruit, and you'll feel more relaxed - it's as sweet as that."
  "Don't get too serious about work. Regrets lie in neglected relationships."
  "Satisfying cravings of any kind is no way to help yourself feel calm. Find an alternative."
  "In Zone Therapy, the backs of the hands are the way to tap into calm."
  "Be rigorous in differentiating between what is achievable, and what is a waste of time."
  "Have you ever noticed a calm person with a loud voice? Try and speak soft once in a while"
  "A cup of warm water will calm you even more than a cup of cold water."
  "Do yourself a favour and from time to time, relax your standards a little."
  "Articulating your ideas can take you to half the way of solving them."
  "Wear light loose clothing. This is why yogis wear white."
  "Practise being calm in a certain place. Then simply go there to become calm."
  "By speaking slowly and calmly, you can spread a feeling of calm within a group."
  "Gardeners are among the most calm and relaxed people."
  "There is something both emotionally and physically soothing about crying."
  "Be more polite, not for the benefit of others, but the ennoblement of yourself."
  "The simplest touch sometimes works miracles."
  "The pace you move has a direct relationship with the way you feel. Slow down."
  "Get on speaking terms with your humour. Access it more than you think is a good thing."
  "Learn to recognize signs of tension and anxiety in others."
  "Clearing out the clutter is and orderly way to calm."
  "By pretending to be calm, you will force your subconscious into believing you are calm."
  "There's more to the simple act of putting your feet up than improved circulation."
  "Quiet is the essense of calm. You can't force quiet, but only accept it when it comes."
  "A dab of lavender not only eases aches and pains, but works wonders in helping you relax."
  "Gently touch your fingers together, and breathe slowly for a minute, and allow the calm to take you."
  "Look out for things that make you laugh. If you see nothing, pretend you see it, then laugh."
  "It's hard to feel tense when you're learning something you want to know."
  "When you recognize that lingering on past regrets is a lack of reality, you can be calm."
  "Any foot doctor will tell you that calmness begins at the feet. Buy better fitting shoes."
  "Substitute coffee or tea with a herbal tea, and your calm will be enhanced many times"
  "Soak your feet, then massage them with moisturizer"
  "When you're tense, go somewhere private and gather yourself for 30 seconds."
  "Relax and be open to change when it visits."
  "Knowing when to move on to the next issue is a skill possessed by many calm people."
  "Slow your breathing, and you will slowly breath yourself calm."
  "Be up for the sunrise, it can be the most precious moment of the day."
  "Certain scents stimulate the production of the relaxing chemical serotonin."
  "Share your life with a pet."
  "Being calm is in itself one of life's great pleasures."
  "Most worries are future-based, and revolve around things that will never happen."
  "Take only one deadline at a time, and you will become master of your own time."

  ])
